### ISSUE TITLE
The prop "interval" is invalid, "(max - min)" cannot be divisible by "interval"

### ISSUE THREAD

**Issue by LiamJMcArthur** [NightCatSama/vue-slider-component#438] opened 2020-02-27 11:10 UTC
#### Describe the bug

I keep getting the error `The prop "interval" is invalid, "(max - min)" cannot be divisible by "interval"`. My min value is 0 and my max value is 15101. I decided to use an interval of 2500. Here's the full logged error output:

```
error msg: The prop "interval" is invalid, "(max - min)" cannot be divisible by "interval";
min: 0;
max: 15101;
interval: 2500;
value: 0,15101;
```

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: Windows 10
 - Vue version: 2.5.22
 - Component Version: 3.0.28

**Comment by conradkleinespel** [comment] 2020-02-27 17:10
This might be a duplicate of https://github.com/NightCatSama/vue-slider-component/issues/352

**Comment by LiamJMcArthur** [comment] 2020-02-28 08:09
You can replicate this issue using [this fiddle](https://jsfiddle.net/7gqkp4Lj/).

**Comment by NightCatSama** [comment] 2020-03-02 10:23
Because 15101 is not divisible by 2500.

If you need custom segmentation, you can use the `data` prop.

**Comment by LiamJMcArthur** [comment] 2020-03-02 10:26
@NightCatSama but the error says it cannot be divisible by it, suggesting that 15101 is divisible by 2500?

**Comment by NightCatSama** [comment] 2020-03-02 17:37
That was an error message, because it couldn't be divisible, so something went wrong.

15101 / 2500 = 6.0404   // wrong
15000 / 2500 = 6            // ok

**Comment by conradkleinespel** [comment] 2020-03-02 19:21
I agree with @LiamJMcArthur . The error message makes it sound like the opposite. It should be `The prop "interval" is invalid, "(max - min)" must be divisible by "interval"`, IMO.

![image](https://user-images.githubusercontent.com/1234006/75709675-6f113c00-5cc3-11ea-882a-4903479a8ec3.png)

**Comment by NightCatSama** [comment] 2020-03-05 09:01
Thanks, it will be modified in the next release.

**Closed by NightCatSama** 2020-03-05 09:01 UTC
Labels: bug

**Comment by tripflex** [comment] 2020-11-29 23:02
For anybody that comes across this, here's how I made it so my component will dynamically calculate the correct value for `max` rounding up.

In my situation the range slider is being configured dynamically by the user, both interval and min/max, so I decided the best way to handle this is to just round "up" the max value to whatever is required to make it work correctly.

Below you will see references to `this.autoMinMax` that's because if the users decide not to manually enter the min/max, it will be automatically generated by an AJAX call to get the data (based on data in database)

Where you see `this.typeConfig` that is object that holds all the user defined configurations

```javascript
computed: {
    selectedValue: {
        get() {
            return this.value
        },
        set(newVal) {
            this.$emit('input', newVal)
        }
    },
    autoMinMax() {
        return parseInt(this.typeConfig.auto_min_max) > 0
    },
    min() {
        return parseFloat(this.autoMinMax ? this.auto_min : this.typeConfig.min)
    },
    max() {
        let max = parseFloat(this.autoMinMax ? this.auto_max : this.typeConfig.max)
        const interval = !('interval' in this.typeConfig) ? 1 : this.typeConfig.interval

        if (this.isValidInterval(this.min, max, interval)) {
            return max
        }

        /**
         * At this point, min/max/interval is not valid, so we need to do the calculation to
         * make max divisible by interval.
         * 
         * We do this by dividing max by interval and using Math.ceil to round up.  We then multiply that by
         * interval to get the valid max value
         * 
         * @type {number}
         */
        max = Math.ceil(max / interval) * interval

        /**
         * We now add min to max, so the range works correctly
         * @type {number}
         */
        max = max + this.min

        return max
    },
},
methods: {
    isValidInterval(min, max, interval) {
        return Number.isInteger((max - min) / interval)
    },
}
```
