### ISSUE TITLE
refresh function missing

### ISSUE THREAD

**Issue by desthercz** [NightCatSama/vue-slider-component#328] opened 2019-03-23 01:21 UTC
Hi, refresh function from v2 no longer works. It seems to be removed. Is there any reason for this? I used it for restarting the component in certain situations and now i am unable to.

 - Component Version: v3.0.16

**Comment by NightCatSama** [comment] 2019-03-23 01:54
What data do you want to reset?

**Comment by senner007** [comment] 2019-03-23 19:51
I need a refresh function as well. There is some strange behavior when the visibility of the slider is toggled. The vue-slider-dot translate goes to minus. What I basically need is a function that recalculates the translate x when it reappears on the screen

**Comment by NightCatSama** [comment] 2019-03-24 03:59
In version 3.0, most of the slider's properties are generated by `get`, so when `prop` changes, it changes automatically. I don't know what I can refresh.

I hope to have an online example to reproduce it.

@desthercz @senner007

**Comment by senner007** [comment] 2019-03-24 15:37
More info : It happens when the container element display is set to none and the window is resized.  
I will try to reproduce with an example

**Comment by senner008** [comment] 2019-03-29 12:12
Sorry I can not reproduce the bug. It seems to be fixed in the latest version

**Comment by NightCatSama** [comment] 2019-04-03 03:00
I closed the issue.

If there is still a problem, open it again.

**Closed by NightCatSama** 2019-04-03 03:00 UTC
Labels: bug
